/**
 * The analyst's case view.
 *
 * Everything needed to action one application, ordered the way an analyst
 * actually reads it: what was decided, why, what it resembles, and what to do.
 *
 * The adverse-action reasons are shown verbatim rather than paraphrased. Under
 * fair-lending rules a declined applicant is entitled to the specific principal
 * reasons for the decision, and those reasons must be the ones that actually
 * drove it - which is why they are derived from the SHAP ordering rather than
 * written by hand or generated by the language model.
 */

import { useState } from 'react';
import { AlertTriangle, Check, Fingerprint, Sparkles, X } from 'lucide-react';
import type { DecisionResult } from '../lib/api';
import { formatPercent, formatProbability } from '../lib/format';
import { DecisionPill, ForceBar, Notice, ThresholdMeter } from './primitives';

export function CaseDetail({
  result,
  actualFraud,
  onVerdict,
  busy,
}: {
  result: DecisionResult | null;
  actualFraud: boolean | null;
  onVerdict: (outcome: 'confirmed_fraud' | 'cleared_genuine') => void;
  busy: boolean;
}) {
  const [recorded, setRecorded] = useState<string | null>(null);

  if (!result) {
    return (
      <Notice
        title="No case selected"
        detail="Select an application from the ledger to see the factors behind its decision."
      />
    );
  }

  const allReasons = [...result.top_risk_factors, ...result.top_protective_factors];
  const maxContribution = Math.max(
    ...allReasons.map((r) => Math.abs(r.contribution)),
    Number.EPSILON,
  );

  const handleVerdict = (outcome: 'confirmed_fraud' | 'cleared_genuine') => {
    onVerdict(outcome);
    setRecorded(outcome);
  };

  return (
    <div className="divide-y divide-line">
      {/* ---------- verdict header ---------- */}
      <div className="px-4 py-3">
        <div className="flex items-start justify-between gap-3">
          <div>
            <div className="num text-[11px] text-ink-3">{result.application_id}</div>
            <div className="mt-1.5 flex items-center gap-2">
              <DecisionPill decision={result.decision} />
              {result.escalated && (
                <span
                  className="num text-[9px] uppercase tracking-wider"
                  style={{ color: 'var(--color-review)' }}
                >
                  escalated from {result.model_decision}
                </span>
              )}
            </div>
          </div>
          <div className="text-right">
            <div className="eyebrow">Fraud probability</div>
            <div className="num mt-0.5 text-2xl leading-none text-ink">
              {formatProbability(result.fraud_probability)}
            </div>
            <div className="mt-1 text-[10px] text-ink-3">
              calibrated · {result.model_version}
            </div>
          </div>
        </div>

        <div className="mt-4">
          <ThresholdMeter
            probability={result.fraud_probability}
            thresholds={result.thresholds}
          />
        </div>

        {result.escalated && result.escalation_reason && (
          <div
            className="mt-3 border-l-2 py-1 pl-2.5 text-[11px] leading-relaxed"
            style={{ borderColor: 'var(--color-review)', color: 'var(--color-ink-2)' }}
          >
            <span className="eyebrow" style={{ color: 'var(--color-review)' }}>
              Rule override
            </span>
            <p className="mt-1">{result.escalation_reason}</p>
            <p className="mt-1 text-[10px] text-ink-3">
              The model is unchanged. A previously confirmed fraud was indexed by an
              analyst, and this application matches it — so the platform raised the
              decision without retraining.
            </p>
          </div>
        )}

        {actualFraud !== null && (
          <div
            className="mt-3 flex items-center gap-2 border px-2.5 py-1.5 text-[11px]"
            style={{
              borderColor: actualFraud ? 'var(--color-block)' : 'var(--color-line-bright)',
              color: actualFraud ? 'var(--color-block)' : 'var(--color-ink-3)',
            }}
          >
            <AlertTriangle size={12} aria-hidden="true" />
            <span>
              Ground truth (replay only): this application was{' '}
              <strong>{actualFraud ? 'fraudulent' : 'genuine'}</strong>
            </span>
          </div>
        )}
      </div>

      {/* ---------- narrative ---------- */}
      <div className="px-4 py-3">
        <div className="flex items-center gap-1.5">
          <Sparkles size={11} className="text-ink-3" aria-hidden="true" />
          <span className="eyebrow">Analyst briefing</span>
          <span
            className="num ml-auto text-[9px] uppercase tracking-wider"
            style={{
              color:
                result.narrative_source === 'gemini'
                  ? 'var(--color-series-1)'
                  : 'var(--color-ink-3)',
            }}
          >
            {result.narrative_source === 'gemini' ? 'Gemini' : 'template'}
          </span>
        </div>
        <p className="mt-2 text-xs leading-relaxed text-ink-2">{result.narrative}</p>
        <p className="mt-2 text-[10px] leading-relaxed text-ink-3">
          Written from the attributions below, after the decision was made. The language
          model cannot change a score, a threshold, or an outcome.
        </p>
      </div>

      {/* ---------- adverse action reasons ---------- */}
      {result.decision !== 'APPROVE' && result.adverse_action_reasons.length > 0 && (
        <div className="px-4 py-3">
          <span className="eyebrow">Principal reasons (adverse action)</span>
          <ol className="mt-2 space-y-1">
            {result.adverse_action_reasons.map((reason, index) => (
              <li key={reason} className="flex gap-2 text-xs text-ink-2">
                <span className="num text-ink-3">{index + 1}.</span>
                <span>{reason}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* ---------- contribution force bars ---------- */}
      <div>
        <div className="flex items-center justify-between px-4 pb-1 pt-3">
          <span className="eyebrow">Why — factor contributions</span>
          <span className="text-[9px] text-ink-3">← lowers risk · raises risk →</span>
        </div>
        <ForceBar reasons={result.top_risk_factors} max={maxContribution} />
        {result.top_protective_factors.length > 0 && (
          <>
            <div className="border-t border-line px-4 pb-1 pt-3">
              <span className="eyebrow">Mitigating factors</span>
            </div>
            <ForceBar reasons={result.top_protective_factors} max={maxContribution} />
          </>
        )}
      </div>

      {/* ---------- similar confirmed fraud ---------- */}
      <div className="px-4 py-3">
        <div className="flex items-center gap-1.5">
          <Fingerprint size={11} className="text-ink-3" aria-hidden="true" />
          <span className="eyebrow">Resembles confirmed fraud</span>
        </div>
        {result.similar_confirmed_cases.length === 0 ? (
          <p className="mt-2 text-[11px] leading-relaxed text-ink-3">
            The confirmed-fraud index is empty. Confirming a fraud below indexes it
            immediately — later lookalikes are flagged without retraining.
          </p>
        ) : (
          <>
            <ul className="mt-2 space-y-1.5">
              {result.similar_confirmed_cases.map((match) => {
                // Strength drives the colour, similarity alone does not.
                // Rendering a 0.42 match in alert red would train analysts to
                // ignore the panel, which is worse than not having it.
                const tone =
                  match.strength === 'strong'
                    ? 'var(--color-block)'
                    : match.strength === 'moderate'
                      ? 'var(--color-review)'
                      : 'var(--color-line-bright)';
                return (
                  <li
                    key={match.case_id}
                    className="flex items-baseline justify-between gap-2 border-l-2 pl-2 text-[11px]"
                    style={{ borderColor: tone }}
                  >
                    <span className="num text-ink-2">{match.case_id}</span>
                    <span className="flex-1 text-[10px] text-ink-3">
                      {match.matched_on.length > 0
                        ? `shares ${match.matched_on.join(', ')}`
                        : 'shared decision paths'}
                    </span>
                    <span
                      className="num text-[9px] uppercase tracking-wider"
                      style={{ color: tone }}
                    >
                      {match.strength}
                    </span>
                    <span className="num w-9 text-right text-ink">
                      {formatPercent(match.similarity, 0)}
                    </span>
                  </li>
                );
              })}
            </ul>
            <p className="mt-2 text-[10px] leading-relaxed text-ink-3">
              {result.similar_confirmed_cases.some((m) => m.strength === 'strong')
                ? 'A strong match fires on 1.3% of genuine applications and 10.2% of fraud — a 7.9× lift. Worth investigating.'
                : 'Nearest cases on file, shown for context. Nothing here resembles this application strongly enough to act on.'}
            </p>
          </>
        )}
      </div>

      {/* ---------- feedback loop ---------- */}
      <div className="px-4 py-3">
        <span className="eyebrow">Record verdict</span>
        <div className="mt-2 flex gap-2">
          <button
            type="button"
            disabled={busy}
            onClick={() => handleVerdict('confirmed_fraud')}
            className="pill flex-1 justify-center py-1.5 transition-colors hover:bg-surface-2 disabled:opacity-40"
            style={{ color: 'var(--color-block)' }}
          >
            <X size={12} aria-hidden="true" />
            Confirm fraud
          </button>
          <button
            type="button"
            disabled={busy}
            onClick={() => handleVerdict('cleared_genuine')}
            className="pill flex-1 justify-center py-1.5 transition-colors hover:bg-surface-2 disabled:opacity-40"
            style={{ color: 'var(--color-approve)' }}
          >
            <Check size={12} aria-hidden="true" />
            Clear as genuine
          </button>
        </div>
        {recorded && (
          <p className="mt-2 text-[10px] text-ink-3">
            {recorded === 'confirmed_fraud'
              ? 'Indexed. Applications resembling this one are flagged from the next request.'
              : 'Recorded as genuine.'}
          </p>
        )}
      </div>
    </div>
  );
}
